
//---------Main Controller Cfg Seq-------------------------------
parameter SEQ_MAIN_WEIGHT_REPS_LOWER_LSB = 0;
parameter SEQ_MAIN_WEIGHT_REPS_LOWER_MSB = MAIN_CTRL_WEIGHT_REPS_LOWER_SIZE - 1;

parameter SEQ_MAIN_WEIGHT_REPS_UPPER_LSB = SEQ_MAIN_WEIGHT_REPS_LOWER_MSB + 1;
parameter SEQ_MAIN_WEIGHT_REPS_UPPER_MSB = OUT_IDX_W;

//---------IFMAPS Cfg Seq-----------------------------------------
parameter SEQ_IFMAPS_Y_LIM_LOWER_LSB         = 0;
parameter SEQ_IFMAPS_Y_LIM_LOWER_MSB         = 1;
parameter SEQ_IFMAPS_Y_LIM_LSB               = SEQ_IFMAPS_Y_LIM_LOWER_MSB + 1;

parameter SEQ_IFMAPS_CH_LIM_LOWER_LSB        = 0;
parameter SEQ_IFMAPS_CH_LIM_LOWER_MSB        = 3;
parameter SEQ_IFMAPS_CH_LIM_LSB              = SEQ_IFMAPS_CH_LIM_LOWER_MSB + 1;

parameter SEQ_IFMAPS_TILE_X_LIM_LOWER_LSB    = 0;
parameter SEQ_IFMAPS_TILE_X_LIM_LOWER_MSB    = 5;
parameter SEQ_IFMAPS_TILE_X_LIM_LSB          = SEQ_IFMAPS_TILE_X_LIM_LOWER_MSB + 1;

parameter SEQ_IFMAPS_TILE_Y_LIM_LOWER_LSB    = 0;
parameter SEQ_IFMAPS_TILE_Y_LIM_LOWER_MSB    = 7;
parameter SEQ_IFMAPS_TILE_Y_LIM_LSB          = SEQ_IFMAPS_TILE_Y_LIM_LOWER_MSB + 1;

parameter SEQ_IFMAPS_DIL_PATTERN_LOWER_LSB   = 0;
parameter SEQ_IFMAPS_DIL_PATTERN_LOWER_MSB   = 9;
parameter SEQ_IFMAPS_DIL_PATTERN_2ND_LSB     = SEQ_IFMAPS_DIL_PATTERN_LOWER_MSB + 1;
parameter SEQ_IFMAPS_DIL_PATTERN_2ND_MSB     = 41;
parameter SEQ_IFMAPS_DIL_PATTERN_UPPER_LSB   = SEQ_IFMAPS_DIL_PATTERN_2ND_MSB + 1;
parameter SEQ_IFMAPS_DIL_PATTERN_MSB         = 63;

parameter SEQ_IFMAPS_LOC_WOFFS_0_LOWER_LSB   = 0;
parameter SEQ_IFMAPS_LOC_WOFFS_0_LOWER_MSB   = 1;
parameter SEQ_IFMAPS_LOC_WOFFS_0_LSB         = SEQ_IFMAPS_LOC_WOFFS_0_LOWER_MSB + 1;
parameter SEQ_IFMAPS_LOC_WOFFS_MSB           = 7;

parameter SEQ_IFMAPS_LOC_WOFFS_4_LOWER_LSB   = 0;
parameter SEQ_IFMAPS_LOC_WOFFS_4_LOWER_MSB   = 1;
parameter SEQ_IFMAPS_LOC_WOFFS_4_LSB         = SEQ_IFMAPS_LOC_WOFFS_4_LOWER_MSB + 1;

//---------Weights Cfg Seq-----------------------------------------
parameter SEQ_WEIGHTS_K_LIM_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_K_LIM_LOWER_MSB = FP_ARITHMETIC ? (WEI_K_LIM_LOWER_SIZE - 1) : 0;
parameter SEQ_WEIGHTS_K_LIM_LSB       = FP_ARITHMETIC ? (SEQ_WEIGHTS_K_LIM_LOWER_MSB + 1) : 0;
parameter SEQ_WEIGHTS_K_LIM_MSB       = WEI_TILE_DIM_SIZE - 1;
    
parameter SEQ_WEIGHTS_TILE_K_LIM_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_TILE_K_LIM_LOWER_MSB = FP_ARITHMETIC ? (WEI_TILE_K_LIM_LOWER_SIZE - 1) : 0;
     
parameter SEQ_WEIGHTS_TILE_K_LIM_LSB        = FP_ARITHMETIC ? (SEQ_WEIGHTS_TILE_K_LIM_LOWER_MSB + 1) : 0;
parameter SEQ_WEIGHTS_TILE_K_LIM_MSB        = WEI_TILE_DIM_SIZE - 1;
parameter SEQ_WEIGHTS_ACTIVE_COLS_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_ACTIVE_COLS_LOWER_MSB = FP_ARITHMETIC ? (WEI_COLS_ACTIVE_LOWER_SIZE - 1) : 0;

parameter SEQ_WEIGHTS_ACTIVE_COLS_LSB = FP_ARITHMETIC ? (SEQ_WEIGHTS_ACTIVE_COLS_LOWER_MSB + 1) : 0;
parameter SEQ_WEIGHTS_ACTIVE_COLS_MSB = COLS_ACTIVE_SIZE - 1;

//---------PSUMS Cfg Seq-----------------------------------------
parameter SEQ_PSUMS_CX_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_CX_STEP_LOWER_MSB = PSUMS_CX_STEP_LOWER_SIZE - 1;
parameter SEQ_PSUMS_CX_STEP_LSB       = SEQ_PSUMS_CX_STEP_LOWER_MSB + 1;
parameter SEQ_PSUMS_CX_STEP_MSB       = PSUMS_TILE_DIM_SIZE - 1;

parameter SEQ_PSUMS_CK_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_CK_STEP_LOWER_MSB = PSUMS_CK_STEP_LOWER_SIZE - 1;
parameter SEQ_PSUMS_CK_STEP_LSB       = SEQ_PSUMS_CK_STEP_LOWER_MSB + 1;
parameter SEQ_PSUMS_CK_STEP_MSB       = PSUMS_TILE_DIM_SIZE - 1;

parameter SEQ_PSUMS_TILE_CY_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_TILE_CY_STEP_LOWER_MSB = PSUMS_TILE_CY_STEP_LOWER_SIZE - 1;
parameter SEQ_PSUMS_TILE_CY_STEP_LSB       = SEQ_PSUMS_TILE_CY_STEP_LOWER_MSB + 1;
parameter SEQ_PSUMS_TILE_CY_STEP_MSB       = PSUMS_TILE_DIM_SIZE - 1;

parameter SEQ_PSUMS_TILE_CK_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_TILE_CK_STEP_LOWER_MSB = PSUMS_TILE_CK_STEP_LOWER_SIZE - 1;
parameter SEQ_PSUMS_TILE_CK_STEP_LSB       = FP_ARITHMETIC ? (SEQ_PSUMS_TILE_CK_STEP_LOWER_MSB + 1) : 0;
parameter SEQ_PSUMS_TILE_CK_STEP_MSB       = PSUMS_TILE_DIM_SIZE - 1;

parameter SEQ_PSUMS_INACTIVE_COLS_LOWER_LSB = 0;
parameter SEQ_PSUMS_INACTIVE_COLS_LOWER_MSB = INT_ARITHMETIC ? (PSUMS_INACTIVE_COLS_LOWER_SIZE - 1) : 0;
parameter SEQ_PSUMS_INACTIVE_COLS_LSB       = INT_ARITHMETIC ? (SEQ_PSUMS_INACTIVE_COLS_LOWER_MSB + 1) : 0;
parameter SEQ_PSUMS_INACTIVE_COLS_MSB       = PARAMS_W - 1;
    