
//---------Weights Cfg Seq-----------------------------------------
parameter SEQ_WEIGHTS_K_LIM_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_K_LIM_LOWER_MSB = 1;
parameter SEQ_WEIGHTS_K_LIM_LSB       = SEQ_WEIGHTS_K_LIM_LOWER_MSB + 1;
    
parameter SEQ_WEIGHTS_TILE_K_LIM_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_TILE_K_LIM_LOWER_MSB = 3;
     
parameter SEQ_WEIGHTS_TILE_K_LIM_LSB        = SEQ_WEIGHTS_TILE_K_LIM_LOWER_MSB + 1;
parameter SEQ_WEIGHTS_ACTIVE_COLS_LOWER_LSB = 0;
parameter SEQ_WEIGHTS_ACTIVE_COLS_LOWER_MSB = 5;

parameter SEQ_WEIGHTS_ACTIVE_COLS_LSB = SEQ_WEIGHTS_ACTIVE_COLS_LOWER_MSB + 1;

//---------PSUMS Cfg Seq-----------------------------------------
parameter SEQ_PSUMS_CX_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_CX_STEP_LOWER_MSB = 1;
parameter SEQ_PSUMS_CX_STEP_LSB       = SEQ_PSUMS_CX_STEP_LOWER_MSB + 1;

parameter SEQ_PSUMS_CK_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_CK_STEP_LOWER_MSB = 3;
parameter SEQ_PSUMS_CK_STEP_LSB       = SEQ_PSUMS_CK_STEP_LOWER_MSB + 1;

parameter SEQ_PSUMS_TILE_CY_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_TILE_CY_STEP_LOWER_MSB = 5;
parameter SEQ_PSUMS_TILE_CY_STEP_LSB       = SEQ_PSUMS_TILE_CY_STEP_LOWER_MSB + 1;

parameter SEQ_PSUMS_TILE_CK_STEP_LOWER_LSB = 0;
parameter SEQ_PSUMS_TILE_CK_STEP_LOWER_MSB = 7;
parameter SEQ_PSUMS_TILE_CK_STEP_LSB       = SEQ_PSUMS_TILE_CK_STEP_LOWER_MSB + 1;

parameter SEQ_PSUMS_INACTIVE_COLS_LOWER_LSB = 0;
parameter SEQ_PSUMS_INACTIVE_COLS_LOWER_MSB = 1;
parameter SEQ_PSUMS_INACTIVE_COLS_LSB       = SEQ_PSUMS_INACTIVE_COLS_LOWER_MSB + 1;
    