/**********DF Controller Config********************* */

//IDX 0
parameter DMA_TILE_X_LIM_LSB          = 0;
parameter DMA_TILE_X_LIM_SIZE         = 16;
parameter DMA_TILE_Y_LIM_LSB          = 16;
parameter DMA_TILE_Y_LIM_SIZE         = 16;

//IDX 1
parameter DMA_TILE_C_LIM_LSB          = 0;
parameter DMA_TILE_C_LIM_SIZE         = 16;
parameter DMA_TILE_K_LIM_LSB          = 16;
parameter DMA_TILE_K_LIM_SIZE         = 16;

//IDX 2..17 (full-word)
parameter DMA_TILE_PSUMS_X_STEP_LSB   = 0;
parameter DMA_TILE_PSUMS_X_STEP_SIZE  = SAURIA_REG_SIZE;
parameter DMA_TILE_PSUMS_Y_STEP_LSB   = 0;
parameter DMA_TILE_PSUMS_Y_STEP_SIZE  = SAURIA_REG_SIZE;
parameter DMA_TILE_PSUMS_K_STEP_LSB   = 0;
parameter DMA_TILE_PSUMS_K_STEP_SIZE  = SAURIA_REG_SIZE;
parameter DMA_TILE_IFMAPS_X_STEP_LSB  = 0;
parameter DMA_TILE_IFMAPS_X_STEP_SIZE = SAURIA_REG_SIZE;
parameter DMA_TILE_IFMAPS_Y_STEP_LSB  = 0;
parameter DMA_TILE_IFMAPS_Y_STEP_SIZE = SAURIA_REG_SIZE;
parameter DMA_TILE_IFMAPS_C_STEP_LSB  = 0;
parameter DMA_TILE_IFMAPS_C_STEP_SIZE = SAURIA_REG_SIZE;
parameter DMA_TILE_WEIGHTS_K_STEP_LSB = 0;
parameter DMA_TILE_WEIGHTS_K_STEP_SIZE= SAURIA_REG_SIZE;
parameter DMA_TILE_WEIGHTS_C_STEP_LSB = 0;
parameter DMA_TILE_WEIGHTS_C_STEP_SIZE= SAURIA_REG_SIZE;
parameter DMA_IFMAPS_Y_LIM_LSB        = 0;
parameter DMA_IFMAPS_Y_LIM_SIZE       = SAURIA_REG_SIZE;
parameter DMA_IFMAPS_C_LIM_LSB        = 0;
parameter DMA_IFMAPS_C_LIM_SIZE       = SAURIA_REG_SIZE;
parameter DMA_PSUMS_Y_STEP_LSB        = 0;
parameter DMA_PSUMS_Y_STEP_SIZE       = SAURIA_REG_SIZE;
parameter DMA_PSUMS_K_STEP_LSB        = 0;
parameter DMA_PSUMS_K_STEP_SIZE       = SAURIA_REG_SIZE;
parameter DMA_IFMAPS_Y_STEP_LSB       = 0;
parameter DMA_IFMAPS_Y_STEP_SIZE      = SAURIA_REG_SIZE;
parameter DMA_IFMAPS_C_STEP_LSB       = 0;
parameter DMA_IFMAPS_C_STEP_SIZE      = SAURIA_REG_SIZE;
parameter DMA_WEIGHTS_W_STEP_LSB      = 0;
parameter DMA_WEIGHTS_W_STEP_SIZE     = SAURIA_REG_SIZE;
parameter DMA_IFMAPS_ETT_LSB          = 0;
parameter DMA_IFMAPS_ETT_SIZE         = SAURIA_REG_SIZE;

//IDX 18
parameter DF_START_SRAMA_ADDR_LSB       = 0;
parameter DF_START_SRAMA_ADDR_SIZE      = SAURIA_REG_SIZE;

//IDX 19
parameter DF_START_SRAMB_ADDR_LSB       = 0;
parameter DF_START_SRAMB_ADDR_SIZE      = SAURIA_REG_SIZE;

//IDX 20
parameter DF_START_SRAMC_ADDR_LSB       = 0;
parameter DF_START_SRAMC_ADDR_SIZE      = SAURIA_REG_SIZE;

//IDX 21
parameter DF_LOOP_ORDER_LSB             = 16;
parameter DF_LOOP_ORDER_SIZE            = 2;

parameter DF_STAND_ALONE_LSB            = 18;
parameter DF_STAND_ALONE_KEEP_A_LSB     = 19;
parameter DF_STAND_ALONE_KEEP_B_LSB     = 20;
parameter DF_STAND_ALONE_KEEP_C_LSB     = 21;

parameter DF_START_LSB                  = 22;
parameter DF_CW_EQ_LSB                  = 23;
parameter DF_CH_EQ_LSB                  = 24;
parameter DF_CK_EQ_LSB                  = 25;
parameter DF_WXFER_OP_LSB               = 31;

/**********Main Controller Dimensions********************* */

//IDX 22
parameter MAIN_CTRL_INC_CNT_LIM_LSB        = 0;
parameter MAIN_CTRL_INC_CNT_LIM_SIZE       = ACT_TILE_DIM_SIZE;

parameter MAIN_CTRL_ACT_REPS_LSB           = MAIN_CTRL_INC_CNT_LIM_LSB + MAIN_CTRL_INC_CNT_LIM_SIZE;
parameter MAIN_CTRL_ACT_REPS_SIZE          = PSUMS_TILE_DIM_SIZE;

parameter MAIN_CTRL_WEIGHT_REPS_LOWER_LSB  = MAIN_CTRL_ACT_REPS_LSB + MAIN_CTRL_ACT_REPS_SIZE;
parameter MAIN_CTRL_WEIGHT_REPS_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter MAIN_CTRL_WEIGHT_REPS_LOWER_SIZE = MAIN_CTRL_WEIGHT_REPS_LOWER_MSB - MAIN_CTRL_WEIGHT_REPS_LOWER_LSB + 1;

//IDX 23
parameter MAIN_CTRL_WEIGHT_REPS_UPPER_LSB  = 0;
parameter MAIN_CTRL_WEIGHT_REPS_UPPER_SIZE = PSUMS_TILE_DIM_SIZE - MAIN_CTRL_WEIGHT_REPS_LOWER_SIZE;

parameter MAIN_CTRL_ZERO_NEGLIGENCE_LSB    = MAIN_CTRL_WEIGHT_REPS_UPPER_LSB + MAIN_CTRL_WEIGHT_REPS_UPPER_SIZE;
parameter MAIN_CTRL_ZERO_NEGLIGENCE_SIZE   = TH_W;

/**********IFMAPS Dimensions********************* */

//IDX 24
parameter IFMAPS_X_LIM_LSB                = 0;
parameter IFMAPS_X_STEP_LSB               = IFMAPS_X_LIM_LSB + ACT_TILE_DIM_SIZE;

parameter IFMAPS_Y_LIM_LOWER_LSB          = IFMAPS_X_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_Y_LIM_LOWER_MSB          = SAURIA_REG_SIZE - 1;
parameter IFMAPS_Y_LIM_LOWER_SIZE         = IFMAPS_Y_LIM_LOWER_MSB - IFMAPS_Y_LIM_LOWER_LSB + 1;

//IDX 25
parameter IFMAPS_Y_LIM_LSB                = 0;
parameter IFMAPS_Y_LIM_MSB                = ACT_TILE_DIM_SIZE - IFMAPS_Y_LIM_LOWER_SIZE - 1;
parameter IFMAPS_Y_LIM_SIZE               = IFMAPS_Y_LIM_MSB - IFMAPS_Y_LIM_LSB + 1;

parameter IFMAPS_Y_STEP_LSB               = IFMAPS_Y_LIM_MSB + 1;

parameter IFMAPS_CH_LIM_LOWER_LSB         = IFMAPS_Y_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_CH_LIM_LOWER_MSB         = SAURIA_REG_SIZE - 1;
parameter IFMAPS_CH_LIM_LOWER_SIZE        = IFMAPS_CH_LIM_LOWER_MSB - IFMAPS_CH_LIM_LOWER_LSB + 1;

//IDX 26
parameter IFMAPS_CH_LIM_LSB               = 0;
parameter IFMAPS_CH_LIM_MSB               = ACT_TILE_DIM_SIZE - IFMAPS_CH_LIM_LOWER_SIZE - 1;
parameter IFMAPS_CH_LIM_SIZE              = IFMAPS_CH_LIM_MSB - IFMAPS_CH_LIM_LSB + 1;

parameter IFMAPS_CH_STEP_LSB              = IFMAPS_CH_LIM_MSB + 1;

parameter IFMAPS_TILE_X_LIM_LOWER_LSB     = IFMAPS_CH_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_TILE_X_LIM_LOWER_MSB     = SAURIA_REG_SIZE - 1;
parameter IFMAPS_TILE_X_LIM_LOWER_SIZE    = IFMAPS_TILE_X_LIM_LOWER_MSB - IFMAPS_TILE_X_LIM_LOWER_LSB + 1;

//IDX 27
parameter IFMAPS_TILE_X_LIM_LSB           = 0;
parameter IFMAPS_TILE_X_LIM_MSB           = ACT_TILE_DIM_SIZE - IFMAPS_TILE_X_LIM_LOWER_SIZE - 1;
parameter IFMAPS_TILE_X_LIM_SIZE          = IFMAPS_TILE_X_LIM_MSB - IFMAPS_TILE_X_LIM_LSB + 1;

parameter IFMAPS_TILE_X_STEP_LSB          = IFMAPS_TILE_X_LIM_MSB + 1;

parameter IFMAPS_TILE_Y_LIM_LOWER_LSB     = IFMAPS_TILE_X_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_TILE_Y_LIM_LOWER_MSB     = SAURIA_REG_SIZE - 1;
parameter IFMAPS_TILE_Y_LIM_LOWER_SIZE    = IFMAPS_TILE_Y_LIM_LOWER_MSB - IFMAPS_TILE_Y_LIM_LOWER_LSB + 1;

//IDX 28
parameter IFMAPS_TILE_Y_LIM_LSB           = 0;
parameter IFMAPS_TILE_Y_LIM_MSB           = ACT_TILE_DIM_SIZE - IFMAPS_TILE_Y_LIM_LOWER_SIZE - 1;
parameter IFMAPS_TILE_Y_LIM_SIZE          = IFMAPS_TILE_Y_LIM_MSB - IFMAPS_TILE_Y_LIM_LSB + 1;

parameter IFMAPS_TILE_Y_STEP_LSB          = IFMAPS_TILE_Y_LIM_MSB + 1;

parameter IFMAPS_DILATION_PATTERN_LOWER_LSB  = IFMAPS_TILE_Y_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_DILATION_PATTERN_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter IFMAPS_DILATION_PATTERN_LOWER_SIZE = IFMAPS_DILATION_PATTERN_LOWER_MSB - IFMAPS_DILATION_PATTERN_LOWER_LSB + 1;

//IDX 29
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_LSB  = 0;
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_MSB  = SAURIA_REG_SIZE - 1;
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_SIZE = IFMAPS_DILATION_PATTERN_2ND_BYTE_MSB - IFMAPS_DILATION_PATTERN_2ND_BYTE_LSB + 1;

//IDX 30
parameter IFMAPS_DILATION_PATTERN_UPPER_LSB  = 0;
parameter IFMAPS_DILATION_PATTERN_UPPER_MSB  = 21;
parameter IFMAPS_DILATION_PATTERN_UPPER_SIZE = IFMAPS_DILATION_PATTERN_UPPER_MSB - IFMAPS_DILATION_PATTERN_UPPER_LSB + 1;

parameter IFMAPS_ROWS_ACTIVE_LSB             = IFMAPS_DILATION_PATTERN_UPPER_MSB + 1;
parameter IFMAPS_ROWS_ACTIVE_MSB             = IFMAPS_ROWS_ACTIVE_LSB + ROWS_ACTIVE_SIZE - 1;
parameter IFMAPS_ROWS_ACTIVE_SIZE            = IFMAPS_ROWS_ACTIVE_MSB - IFMAPS_ROWS_ACTIVE_LSB + 1;

parameter IFMAPS_LOC_WOFFS_0_LOWER_LSB       = IFMAPS_ROWS_ACTIVE_MSB + 1;
parameter IFMAPS_LOC_WOFFS_0_LOWER_MSB       = SAURIA_REG_SIZE - 1;
parameter IFMAPS_LOC_WOFFS_0_LOWER_SIZE      = IFMAPS_LOC_WOFFS_0_LOWER_MSB - IFMAPS_LOC_WOFFS_0_LOWER_LSB + 1;

//IDX 31
parameter IFMAPS_LOC_WOFFS_0_LSB             = 0;
parameter IFMAPS_LOC_WOFFS_0_MSB             = 7 - IFMAPS_LOC_WOFFS_0_LOWER_SIZE;
parameter IFMAPS_LOC_WOFFS_0_SIZE            = IFMAPS_LOC_WOFFS_0_MSB - IFMAPS_LOC_WOFFS_0_LSB + 1;

parameter IFMAPS_LOC_WOFFS_1_LSB             = IFMAPS_LOC_WOFFS_0_MSB + 1;
parameter IFMAPS_LOC_WOFFS_1_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_2_LSB             = IFMAPS_LOC_WOFFS_1_LSB + IFMAPS_LOC_WOFFS_1_SIZE;
parameter IFMAPS_LOC_WOFFS_2_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_3_LSB             = IFMAPS_LOC_WOFFS_2_LSB + IFMAPS_LOC_WOFFS_2_SIZE;
parameter IFMAPS_LOC_WOFFS_3_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_4_LOWER_LSB       = IFMAPS_LOC_WOFFS_3_LSB + IFMAPS_LOC_WOFFS_3_SIZE;
parameter IFMAPS_LOC_WOFFS_4_LOWER_MSB       = SAURIA_REG_SIZE - 1;
parameter IFMAPS_LOC_WOFFS_4_LOWER_SIZE      = IFMAPS_LOC_WOFFS_4_LOWER_MSB - IFMAPS_LOC_WOFFS_4_LOWER_LSB + 1;

//IDX 32
parameter IFMAPS_LOC_WOFFS_4_LSB             = 0;
parameter IFMAPS_LOC_WOFFS_4_MSB             = 7 - IFMAPS_LOC_WOFFS_4_LOWER_SIZE;
parameter IFMAPS_LOC_WOFFS_4_SIZE            = IFMAPS_LOC_WOFFS_4_MSB - IFMAPS_LOC_WOFFS_4_LSB + 1;

parameter IFMAPS_LOC_WOFFS_5_LSB             = IFMAPS_LOC_WOFFS_4_MSB + 1;
parameter IFMAPS_LOC_WOFFS_5_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_6_LSB             = IFMAPS_LOC_WOFFS_5_LSB + IFMAPS_LOC_WOFFS_5_SIZE;
parameter IFMAPS_LOC_WOFFS_6_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_7_LSB             = IFMAPS_LOC_WOFFS_6_LSB + IFMAPS_LOC_WOFFS_6_SIZE;
parameter IFMAPS_LOC_WOFFS_7_SIZE            = 8;

/**********Weights Dimensions********************* */
    
//IDX 33
parameter WEI_W_LIM_LSB              = 0;
parameter WEI_W_STEP_LSB             = WEI_W_LIM_LSB   + WEI_TILE_DIM_SIZE;

parameter WEI_K_LIM_LOWER_LSB        = WEI_W_STEP_LSB  + WEI_TILE_DIM_SIZE;           //FP-Only
parameter WEI_K_LIM_LOWER_MSB        = FP_ARITHMETIC ? (SAURIA_REG_SIZE - 1) : WEI_K_LIM_LOWER_LSB; //FP-Only
parameter WEI_K_LIM_LOWER_SIZE       = FP_ARITHMETIC ? (WEI_K_LIM_LOWER_MSB - WEI_K_LIM_LOWER_LSB + 1) : 0; //FP-Only

//IDX 34
parameter WEI_K_LIM_LSB              = 0;
parameter WEI_K_LIM_MSB              = WEI_TILE_DIM_SIZE - WEI_K_LIM_LOWER_SIZE - 1;
parameter WEI_K_LIM_SIZE             = WEI_K_LIM_MSB - WEI_K_LIM_LSB + 1;
parameter WEI_K_STEP_LSB             = WEI_K_LIM_MSB  + 1;
    
parameter WEI_TILE_K_LIM_LOWER_LSB   =  WEI_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_TILE_K_LIM_LOWER_MSB   = FP_ARITHMETIC ? (SAURIA_REG_SIZE - 1) : WEI_TILE_K_LIM_LOWER_LSB;
parameter WEI_TILE_K_LIM_LOWER_SIZE  = FP_ARITHMETIC ? (WEI_TILE_K_LIM_LOWER_MSB - WEI_TILE_K_LIM_LOWER_LSB + 1) : 0;

//IDX 35
parameter WEI_TILE_K_LIM_LSB         = 0;
parameter WEI_TILE_K_LIM_MSB         = WEI_TILE_DIM_SIZE - WEI_TILE_K_LIM_LOWER_SIZE - 1;
parameter WEI_TILE_K_LIM_SIZE        = WEI_TILE_K_LIM_MSB - WEI_TILE_K_LIM_LSB + 1;

parameter WEI_TILE_K_STEP_LSB        = WEI_TILE_K_LIM_MSB + 1;
    
parameter WEI_COLS_ACTIVE_LOWER_LSB  = WEI_TILE_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_COLS_ACTIVE_LOWER_MSB  = FP_ARITHMETIC ? (SAURIA_REG_SIZE - 1) : WEI_COLS_ACTIVE_LOWER_LSB;
parameter WEI_COLS_ACTIVE_LOWER_SIZE = FP_ARITHMETIC ? (WEI_COLS_ACTIVE_LOWER_MSB - WEI_COLS_ACTIVE_LOWER_LSB + 1) : 0;
   
//IDX 36
parameter WEI_COLS_ACTIVE_LSB        = 0;
parameter WEI_COLS_ACTIVE_SIZE       = COLS_ACTIVE_SIZE - WEI_COLS_ACTIVE_LOWER_SIZE;
parameter WEI_COLS_ACTIVE_MSB        = WEI_COLS_ACTIVE_LSB + WEI_COLS_ACTIVE_SIZE - 1;

parameter WEI_ALIGNED_FLAG_LSB       = WEI_COLS_ACTIVE_MSB + 1;

/**********PSUMS Dimensions********************* */

//IDX 37
parameter PSUMS_REPS_LSB                 = 0;
parameter PSUMS_CX_LIM_LSB               = PSUMS_REPS_LSB + PSUMS_TILE_DIM_SIZE;

parameter PSUMS_CX_STEP_LOWER_LSB        = PSUMS_CX_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CX_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CX_STEP_LOWER_SIZE       = PSUMS_CX_STEP_LOWER_MSB - PSUMS_CX_STEP_LOWER_LSB + 1;

//IDX 38
parameter PSUMS_CX_STEP_LSB              = 0;
parameter PSUMS_CX_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CX_STEP_LOWER_SIZE - 1;
parameter PSUMS_CX_STEP_SIZE             = PSUMS_CX_STEP_MSB - PSUMS_CX_STEP_LSB + 1;

parameter PSUMS_CK_LIM_LSB               = PSUMS_CX_STEP_MSB + 1;

parameter PSUMS_CK_STEP_LOWER_LSB        = PSUMS_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CK_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CK_STEP_LOWER_SIZE       = PSUMS_CK_STEP_LOWER_MSB - PSUMS_CK_STEP_LOWER_LSB + 1;

//IDX 39
parameter PSUMS_CK_STEP_LSB              = 0;
parameter PSUMS_CK_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CK_STEP_LOWER_SIZE - 1;
parameter PSUMS_CK_STEP_SIZE             = PSUMS_CK_STEP_MSB - PSUMS_CK_STEP_LSB + 1;

parameter PSUMS_TILE_CY_LIM_LSB          = PSUMS_CK_STEP_MSB + 1;

parameter PSUMS_TILE_CY_STEP_LOWER_LSB   = PSUMS_TILE_CY_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CY_STEP_LOWER_MSB   = SAURIA_REG_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_LOWER_SIZE  = PSUMS_TILE_CY_STEP_LOWER_MSB - PSUMS_TILE_CY_STEP_LOWER_LSB + 1;

//IDX 40
parameter PSUMS_TILE_CY_STEP_LSB         = 0;
parameter PSUMS_TILE_CY_STEP_MSB         = PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CY_STEP_LOWER_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_SIZE        = PSUMS_TILE_CY_STEP_MSB - PSUMS_TILE_CY_STEP_LSB + 1;

parameter PSUMS_TILE_CK_LIM_LSB          = PSUMS_TILE_CY_STEP_MSB + 1;

parameter PSUMS_TILE_CK_STEP_LOWER_LSB   = PSUMS_TILE_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CK_STEP_LOWER_SIZE  = FP_ARITHMETIC ? (SAURIA_REG_SIZE - PSUMS_TILE_CK_STEP_LOWER_LSB) : PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CK_STEP_LOWER_MSB   = PSUMS_TILE_CK_STEP_LOWER_LSB + PSUMS_TILE_CK_STEP_LOWER_SIZE - 1;

parameter PSUMS_INACTIVE_COLS_LOWER_LSB  = PSUMS_TILE_CK_STEP_LOWER_MSB + 1; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_SIZE = INT_ARITHMETIC ? (SAURIA_REG_SIZE - PSUMS_INACTIVE_COLS_LOWER_LSB) : 0; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_MSB  = PSUMS_INACTIVE_COLS_LOWER_LSB + PSUMS_INACTIVE_COLS_LOWER_SIZE - 1; //INT-Only

//IDX 41
parameter PSUMS_TILE_CK_STEP_LSB         = 0;
parameter PSUMS_TILE_CK_STEP_MSB         = FP_ARITHMETIC ? (PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CK_STEP_LOWER_SIZE - 1) : -1;
parameter PSUMS_TILE_CK_STEP_SIZE        = PSUMS_TILE_CK_STEP_MSB - PSUMS_TILE_CK_STEP_LSB + 1;

parameter PSUMS_INACTIVE_COLS_LSB        = INT_ARITHMETIC ? 0 : (PSUMS_TILE_CK_STEP_MSB + 1);
parameter PSUMS_INACTIVE_COLS_SIZE       = INT_ARITHMETIC ? (PARAMS_W - PSUMS_INACTIVE_COLS_LOWER_SIZE) : PARAMS_W;
parameter PSUMS_INACTIVE_COLS_MSB        = PSUMS_INACTIVE_COLS_LSB + PSUMS_INACTIVE_COLS_SIZE - 1;

parameter PSUMS_PRELOAD_EN_LSB           = PSUMS_INACTIVE_COLS_MSB + 1;

/**********Ctrl Status Registers********************* */

// ctrl_status_reg_0 (offset 0x0) - Control & Status
parameter CTRL_STATUS_START_LSB             = 0;
parameter CTRL_STATUS_START_SIZE            = 1;
parameter CTRL_STATUS_DONE_LSB              = 1;
parameter CTRL_STATUS_DONE_SIZE             = 1;
parameter CTRL_STATUS_IDLE_LSB              = 2;
parameter CTRL_STATUS_IDLE_SIZE             = 1;
parameter CTRL_STATUS_READY_LSB             = 3;
parameter CTRL_STATUS_READY_SIZE            = 1;
parameter CTRL_STATUS_AUTO_RESTART_LSB      = 7;
parameter CTRL_STATUS_AUTO_RESTART_SIZE     = 1;
parameter CTRL_STATUS_MEM_SWITCH_LSB        = 16;
parameter CTRL_STATUS_MEM_SWITCH_SIZE       = 1;
parameter CTRL_STATUS_MEM_KEEP_A_LSB        = 17;
parameter CTRL_STATUS_MEM_KEEP_A_SIZE       = 1;
parameter CTRL_STATUS_MEM_KEEP_B_LSB        = 18;
parameter CTRL_STATUS_MEM_KEEP_B_SIZE       = 1;
parameter CTRL_STATUS_MEM_KEEP_C_LSB        = 19;
parameter CTRL_STATUS_MEM_KEEP_C_SIZE       = 1;
parameter CTRL_STATUS_IMPLICIT_MAP_LSB      = 24;
parameter CTRL_STATUS_IMPLICIT_MAP_SIZE     = 1;

parameter CTRL_STATUS_SOFT_RESET_LSB        = 31;
parameter CTRL_STATUS_SOFT_RESET_SIZE       = 1;

// ctrl_status_reg_1 (offset 0x4) - Global Interrupt Enable
parameter CTRL_STATUS_GLOBAL_INT_EN_LSB     = 0;
parameter CTRL_STATUS_GLOBAL_INT_EN_SIZE    = 1;

// ctrl_status_reg_2 (offset 0x8) - Done Interrupt Enable
parameter CTRL_STATUS_DONE_INT_EN_LSB       = 0;
parameter CTRL_STATUS_DONE_INT_EN_SIZE      = 1;

// ctrl_status_reg_3 (offset 0xC) - Done Interrupt Status
parameter CTRL_STATUS_DONE_INT_STATUS_LSB   = 0;
parameter CTRL_STATUS_DONE_INT_STATUS_SIZE  = 1;

// ctrl_status_reg_4 (offset 0x14) - Status Flags
parameter CTRL_STATUS_STATUS_FLAGS_LSB      = 0;
parameter CTRL_STATUS_STATUS_FLAGS_SIZE     = SAURIA_REG_SIZE;

// ctrl_status_reg_5 (offset 0x180) - Cycle Counter
parameter CTRL_STATUS_CYCLE_COUNTER_LSB     = 0;
parameter CTRL_STATUS_CYCLE_COUNTER_SIZE    = SAURIA_REG_SIZE;

// ctrl_status_reg_6 (offset 0x184) - Stalls Counter
parameter CTRL_STATUS_STALLS_COUNTER_LSB    = 0;
parameter CTRL_STATUS_STALLS_COUNTER_SIZE   = SAURIA_REG_SIZE;

// Register address offsets within the ctrl_status block
parameter CTRL_STATUS_BASE_OFFSET    = CFG_BASE_OFFSET;
parameter CTRL_STATUS_REG_0_ADDR = 'h0;
parameter CTRL_STATUS_REG_1_ADDR = 'h4;
parameter CTRL_STATUS_REG_2_ADDR = 'h8;
parameter CTRL_STATUS_REG_3_ADDR = 'hC;
parameter CTRL_STATUS_REG_4_ADDR = 'h10;
parameter CTRL_STATUS_REG_5_ADDR = 'h14;
parameter CTRL_STATUS_REG_6_ADDR = 'h18;
parameter NUM_CTRL_STATUS_REGS   = 7;
