/**********Main Controller Dimensions********************* */

//IDX 22
parameter MAIN_CTRL_INC_CNT_LIM_LSB        = 0;
parameter MAIN_CTRL_INC_CNT_LIM_SIZE       = ACT_TILE_DIM_SIZE;

parameter MAIN_CTRL_ACT_REPS_LSB           = MAIN_CTRL_INC_CNT_LIM_LSB + MAIN_CTRL_INC_CNT_LIM_SIZE;
parameter MAIN_CTRL_ACT_REPS_SIZE          = PSUMS_TILE_DIM_SIZE;

parameter MAIN_CTRL_WEIGHT_REPS_LOWER_LSB  = MAIN_CTRL_ACT_REPS_LSB + MAIN_CTRL_ACT_REPS_SIZE;
parameter MAIN_CTRL_WEIGHT_REPS_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter MAIN_CTRL_WEIGHT_REPS_LOWER_SIZE = MAIN_CTRL_WEIGHT_REPS_LOWER_MSB - MAIN_CTRL_WEIGHT_REPS_LOWER_LSB + 1;

//IDX 23
parameter MAIN_CTRL_WEIGHT_REPS_UPPER_LSB  = 0;
parameter MAIN_CTRL_WEIGHT_REPS_UPPER_SIZE = PSUMS_TILE_DIM_SIZE - MAIN_CTRL_WEIGHT_REPS_LOWER_SIZE;

parameter MAIN_CTRL_ZERO_NEGLIGENCE_LSB    = MAIN_CTRL_WEIGHT_REPS_UPPER_LSB + MAIN_CTRL_WEIGHT_REPS_UPPER_SIZE;
parameter MAIN_CTRL_ZERO_NEGLIGENCE_SIZE   = TH_W;

/**********IFMAPS Dimensions********************* */

//IDX 24
parameter IFMAPS_X_LIM_LSB                = 0;
parameter IFMAPS_X_STEP_LSB               = IFMAPS_X_LIM_LSB + ACT_TILE_DIM_SIZE;

parameter IFMAPS_Y_LIM_LOWER_LSB          = IFMAPS_X_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_Y_LIM_LOWER_MSB          = SAURIA_REG_SIZE - 1;
parameter IFMAPS_Y_LIM_LOWER_SIZE         = IFMAPS_Y_LIM_LOWER_MSB - IFMAPS_Y_LIM_LOWER_LSB + 1;

//IDX 25
parameter IFMAPS_Y_LIM_LSB                = 0;
parameter IFMAPS_Y_LIM_MSB                = ACT_TILE_DIM_SIZE - IFMAPS_Y_LIM_LOWER_SIZE - 1;
parameter IFMAPS_Y_LIM_SIZE               = IFMAPS_Y_LIM_MSB - IFMAPS_Y_LIM_LSB + 1;

parameter IFMAPS_Y_STEP_LSB               = IFMAPS_Y_LIM_MSB + 1;

parameter IFMAPS_CH_LIM_LOWER_LSB         = IFMAPS_Y_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_CH_LIM_LOWER_MSB         = SAURIA_REG_SIZE - 1;
parameter IFMAPS_CH_LIM_LOWER_SIZE        = IFMAPS_CH_LIM_LOWER_MSB - IFMAPS_CH_LIM_LOWER_LSB + 1;

//IDX 26
parameter IFMAPS_CH_LIM_LSB               = 0;
parameter IFMAPS_CH_LIM_MSB               = ACT_TILE_DIM_SIZE - IFMAPS_CH_LIM_LOWER_SIZE - 1;
parameter IFMAPS_CH_LIM_SIZE              = IFMAPS_CH_LIM_MSB - IFMAPS_CH_LIM_LSB + 1;

parameter IFMAPS_CH_STEP_LSB              = IFMAPS_CH_LIM_MSB + 1;

parameter IFMAPS_TILE_X_LIM_LOWER_LSB     = IFMAPS_CH_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_TILE_X_LIM_LOWER_MSB     = SAURIA_REG_SIZE - 1;
parameter IFMAPS_TILE_X_LIM_LOWER_SIZE    = IFMAPS_TILE_X_LIM_LOWER_MSB - IFMAPS_TILE_X_LIM_LOWER_LSB + 1;

//IDX 27
parameter IFMAPS_TILE_X_LIM_LSB           = 0;
parameter IFMAPS_TILE_X_LIM_MSB           = ACT_TILE_DIM_SIZE - IFMAPS_TILE_X_LIM_LOWER_SIZE - 1;
parameter IFMAPS_TILE_X_LIM_SIZE          = IFMAPS_TILE_X_LIM_MSB - IFMAPS_TILE_X_LIM_LSB + 1;

parameter IFMAPS_TILE_X_STEP_LSB          = IFMAPS_TILE_X_LIM_MSB + 1;

parameter IFMAPS_TILE_Y_LIM_LOWER_LSB     = IFMAPS_TILE_X_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_TILE_Y_LIM_LOWER_MSB     = SAURIA_REG_SIZE - 1;
parameter IFMAPS_TILE_Y_LIM_LOWER_SIZE    = IFMAPS_TILE_Y_LIM_LOWER_MSB - IFMAPS_TILE_Y_LIM_LOWER_LSB + 1;

//IDX 28
parameter IFMAPS_TILE_Y_LIM_LSB           = 0;
parameter IFMAPS_TILE_Y_LIM_MSB           = ACT_TILE_DIM_SIZE - IFMAPS_TILE_Y_LIM_LOWER_SIZE - 1;
parameter IFMAPS_TILE_Y_LIM_SIZE          = IFMAPS_TILE_Y_LIM_MSB - IFMAPS_TILE_Y_LIM_LSB + 1;

parameter IFMAPS_TILE_Y_STEP_LSB          = IFMAPS_TILE_Y_LIM_MSB + 1;

parameter IFMAPS_DILATION_PATTERN_LOWER_LSB  = IFMAPS_TILE_Y_STEP_LSB + ACT_TILE_DIM_SIZE;
parameter IFMAPS_DILATION_PATTERN_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter IFMAPS_DILATION_PATTERN_LOWER_SIZE = IFMAPS_DILATION_PATTERN_LOWER_MSB - IFMAPS_DILATION_PATTERN_LOWER_LSB + 1;

//IDX 29
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_LSB  = 0;
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_MSB  = SAURIA_REG_SIZE - 1;
parameter IFMAPS_DILATION_PATTERN_2ND_BYTE_SIZE = IFMAPS_DILATION_PATTERN_2ND_BYTE_MSB - IFMAPS_DILATION_PATTERN_2ND_BYTE_LSB + 1;

//IDX 30
parameter IFMAPS_DILATION_PATTERN_UPPER_LSB  = 0;
parameter IFMAPS_DILATION_PATTERN_UPPER_MSB  = 21;
parameter IFMAPS_DILATION_PATTERN_UPPER_SIZE = IFMAPS_DILATION_PATTERN_UPPER_MSB - IFMAPS_DILATION_PATTERN_UPPER_LSB + 1;

parameter IFMAPS_ROWS_ACTIVE_LSB             = IFMAPS_DILATION_PATTERN_UPPER_MSB + 1;
parameter IFMAPS_ROWS_ACTIVE_MSB             = IFMAPS_ROWS_ACTIVE_LSB + ROWS_ACTIVE_SIZE - 1;
parameter IFMAPS_ROWS_ACTIVE_SIZE            = IFMAPS_ROWS_ACTIVE_MSB - IFMAPS_ROWS_ACTIVE_LSB + 1;

parameter IFMAPS_LOC_WOFFS_0_LOWER_LSB       = IFMAPS_ROWS_ACTIVE_MSB + 1;
parameter IFMAPS_LOC_WOFFS_0_LOWER_MSB       = SAURIA_REG_SIZE - 1;
parameter IFMAPS_LOC_WOFFS_0_LOWER_SIZE      = IFMAPS_LOC_WOFFS_0_LOWER_MSB - IFMAPS_LOC_WOFFS_0_LOWER_LSB + 1;

//IDX 31
parameter IFMAPS_LOC_WOFFS_0_LSB             = 0;
parameter IFMAPS_LOC_WOFFS_0_MSB             = 7 - IFMAPS_LOC_WOFFS_0_LOWER_SIZE;
parameter IFMAPS_LOC_WOFFS_0_SIZE            = IFMAPS_LOC_WOFFS_0_MSB - IFMAPS_LOC_WOFFS_0_LSB + 1;

parameter IFMAPS_LOC_WOFFS_1_LSB             = IFMAPS_LOC_WOFFS_0_MSB + 1;
parameter IFMAPS_LOC_WOFFS_1_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_2_LSB             = IFMAPS_LOC_WOFFS_1_LSB + IFMAPS_LOC_WOFFS_1_SIZE;
parameter IFMAPS_LOC_WOFFS_2_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_3_LSB             = IFMAPS_LOC_WOFFS_2_LSB + IFMAPS_LOC_WOFFS_2_SIZE;
parameter IFMAPS_LOC_WOFFS_3_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_4_LOWER_LSB       = IFMAPS_LOC_WOFFS_3_LSB + IFMAPS_LOC_WOFFS_3_SIZE;
parameter IFMAPS_LOC_WOFFS_4_LOWER_MSB       = SAURIA_REG_SIZE - 1;
parameter IFMAPS_LOC_WOFFS_4_LOWER_SIZE      = IFMAPS_LOC_WOFFS_4_LOWER_MSB - IFMAPS_LOC_WOFFS_4_LOWER_LSB + 1;

//IDX 32
parameter IFMAPS_LOC_WOFFS_4_LSB             = 0;
parameter IFMAPS_LOC_WOFFS_4_MSB             = 7 - IFMAPS_LOC_WOFFS_4_LOWER_SIZE;
parameter IFMAPS_LOC_WOFFS_4_SIZE            = IFMAPS_LOC_WOFFS_4_MSB - IFMAPS_LOC_WOFFS_4_LSB + 1;

parameter IFMAPS_LOC_WOFFS_5_LSB             = IFMAPS_LOC_WOFFS_4_MSB + 1;
parameter IFMAPS_LOC_WOFFS_5_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_6_LSB             = IFMAPS_LOC_WOFFS_5_LSB + IFMAPS_LOC_WOFFS_5_SIZE;
parameter IFMAPS_LOC_WOFFS_6_SIZE            = 8;

parameter IFMAPS_LOC_WOFFS_7_LSB             = IFMAPS_LOC_WOFFS_6_LSB + IFMAPS_LOC_WOFFS_6_SIZE;
parameter IFMAPS_LOC_WOFFS_7_SIZE            = 8;

/**********Weights Dimensions********************* */
    
//IDX 33
parameter WEI_W_LIM_LSB              = 0;
parameter WEI_W_STEP_LSB             = WEI_W_LIM_LSB   + WEI_TILE_DIM_SIZE;

parameter WEI_K_LIM_LOWER_LSB        = WEI_W_STEP_LSB  + WEI_TILE_DIM_SIZE;           //FP-Only
parameter WEI_K_LIM_LOWER_MSB        = SAURIA_REG_SIZE - 1;                           //FP-Only
parameter WEI_K_LIM_LOWER_SIZE       = WEI_K_LIM_LOWER_MSB - WEI_K_LIM_LOWER_LSB + 1; //FP-Only

//IDX 34
parameter WEI_K_LIM_LSB              = 0;
parameter WEI_K_LIM_MSB              = WEI_TILE_DIM_SIZE - WEI_K_LIM_LOWER_SIZE - 1;
parameter WEI_K_LIM_SIZE             = WEI_K_LIM_MSB - WEI_K_LIM_LSB + 1;
parameter WEI_K_STEP_LSB             = WEI_K_LIM_MSB  + 1;
    
parameter WEI_TILE_K_LIM_LOWER_LSB   =  WEI_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_TILE_K_LIM_LOWER_MSB   = SAURIA_REG_SIZE - 1;;
parameter WEI_TILE_K_LIM_LOWER_SIZE  = WEI_TILE_K_LIM_LOWER_MSB - WEI_TILE_K_LIM_LOWER_LSB + 1;

//IDX 35
parameter WEI_TILE_K_LIM_LSB         = 0;
parameter WEI_TILE_K_LIM_MSB         = WEI_TILE_DIM_SIZE - WEI_TILE_K_LIM_LOWER_SIZE - 1;
parameter WEI_TILE_K_LIM_SIZE        = WEI_TILE_K_LIM_MSB - WEI_TILE_K_LIM_LSB + 1;

parameter WEI_TILE_K_STEP_LSB        = WEI_TILE_K_LIM_MSB + 1;
    
parameter WEI_COLS_ACTIVE_LOWER_LSB  = WEI_TILE_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_COLS_ACTIVE_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter WEI_COLS_ACTIVE_LOWER_SIZE = WEI_COLS_ACTIVE_LOWER_MSB - WEI_COLS_ACTIVE_LOWER_LSB + 1;
   
//IDX 36
parameter WEI_COLS_ACTIVE_LSB        = 0;
parameter WEI_COLS_ACTIVE_SIZE       = COLS_ACTIVE_SIZE - WEI_COLS_ACTIVE_LOWER_SIZE;
parameter WEI_COLS_ACTIVE_MSB        = WEI_COLS_ACTIVE_LSB + WEI_COLS_ACTIVE_SIZE - 1;

parameter WEI_ALIGNED_FLAG_LSB       = WEI_COLS_ACTIVE_MSB + 1;

/**********PSUMS Dimensions********************* */

//IDX 37
parameter PSUMS_REPS_LSB                 = 0;
parameter PSUMS_CX_LIM_LSB               = PSUMS_REPS_LSB + PSUMS_TILE_DIM_SIZE;

parameter PSUMS_CX_STEP_LOWER_LSB        = PSUMS_CX_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CX_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CX_STEP_LOWER_SIZE       = PSUMS_CX_STEP_LOWER_MSB - PSUMS_CX_STEP_LOWER_LSB + 1;

//IDX 38
parameter PSUMS_CX_STEP_LSB              = 0;
parameter PSUMS_CX_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CX_STEP_LOWER_SIZE - 1;
parameter PSUMS_CX_STEP_SIZE             = PSUMS_CX_STEP_MSB - PSUMS_CX_STEP_LSB + 1;

parameter PSUMS_CK_LIM_LSB               = PSUMS_CX_STEP_MSB + 1;

parameter PSUMS_CK_STEP_LOWER_LSB        = PSUMS_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CK_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CK_STEP_LOWER_SIZE       = PSUMS_CK_STEP_LOWER_MSB - PSUMS_CK_STEP_LOWER_LSB + 1;

//IDX 39
parameter PSUMS_CK_STEP_LSB              = 0;
parameter PSUMS_CK_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CK_STEP_LOWER_SIZE - 1;
parameter PSUMS_CK_STEP_SIZE             = PSUMS_CK_STEP_MSB - PSUMS_CK_STEP_LSB + 1;

parameter PSUMS_TILE_CY_LIM_LSB          = PSUMS_CK_STEP_MSB + 1;

parameter PSUMS_TILE_CY_STEP_LOWER_LSB   = PSUMS_TILE_CY_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CY_STEP_LOWER_MSB   = SAURIA_REG_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_LOWER_SIZE  = PSUMS_TILE_CY_STEP_LOWER_MSB - PSUMS_TILE_CY_STEP_LOWER_LSB + 1;

//IDX 40
parameter PSUMS_TILE_CY_STEP_LSB         = 0;
parameter PSUMS_TILE_CY_STEP_MSB         = PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CY_STEP_LOWER_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_SIZE        = PSUMS_TILE_CY_STEP_MSB - PSUMS_TILE_CY_STEP_LSB + 1;

parameter PSUMS_TILE_CK_LIM_LSB          = PSUMS_TILE_CY_STEP_MSB + 1;

parameter PSUMS_TILE_CK_STEP_LOWER_LSB   = PSUMS_TILE_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CK_STEP_LOWER_MSB   = SAURIA_REG_SIZE - 1;
parameter PSUMS_TILE_CK_STEP_LOWER_SIZE  = PSUMS_TILE_CK_STEP_LOWER_MSB - PSUMS_TILE_CK_STEP_LOWER_LSB + 1;

parameter PSUMS_INACTIVE_COLS_LOWER_LSB  = SAURIA_REG_SIZE - 2; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_MSB  = SAURIA_REG_SIZE - 1; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_SIZE = PSUMS_INACTIVE_COLS_LOWER_MSB - PSUMS_INACTIVE_COLS_LOWER_LSB + 1; //INT-Only

//IDX 41
parameter PSUMS_TILE_CK_STEP_LSB         = 0;
parameter PSUMS_TILE_CK_STEP_MSB         = PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CK_STEP_LOWER_SIZE - 1;
parameter PSUMS_TILE_CK_STEP_SIZE        = PSUMS_TILE_CK_STEP_MSB - PSUMS_TILE_CK_STEP_LSB + 1;

parameter PSUMS_INACTIVE_COLS_LSB        = PSUMS_TILE_CK_STEP_MSB + 1;
parameter PSUMS_INACTIVE_COLS_SIZE       = COLS_ACTIVE_SIZE;
parameter PSUMS_INACTIVE_COLS_MSB        = PSUMS_INACTIVE_COLS_LSB + PSUMS_INACTIVE_COLS_SIZE - 1;

parameter PSUMS_PRELOAD_EN_LSB           = PSUMS_INACTIVE_COLS_MSB + 1;
