/**********Weights Dimensions********************* */
    
//IDX 33
parameter WEI_W_LIM_LSB              = 0;
parameter WEI_W_STEP_LSB             = WEI_W_LIM_LSB   + WEI_TILE_DIM_SIZE;

parameter WEI_K_LIM_LOWER_LSB        = WEI_W_STEP_LSB  + WEI_TILE_DIM_SIZE;           //FP-Only
parameter WEI_K_LIM_LOWER_MSB        = SAURIA_REG_SIZE - 1;                           //FP-Only
parameter WEI_K_LIM_LOWER_SIZE       = WEI_K_LIM_LOWER_MSB - WEI_K_LIM_LOWER_LSB + 1; //FP-Only

//IDX 34
parameter WEI_K_LIM_LSB              = 0;
parameter WEI_K_LIM_MSB              = WEI_TILE_DIM_SIZE - WEI_K_LIM_LOWER_SIZE - 1;
parameter WEI_K_LIM_SIZE             = WEI_K_LIM_MSB - WEI_K_LIM_LSB + 1;
parameter WEI_K_STEP_LSB             = WEI_K_LIM_MSB  + 1;
    
parameter WEI_TILE_K_LIM_LOWER_LSB   =  WEI_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_TILE_K_LIM_LOWER_MSB   = SAURIA_REG_SIZE - 1;;
parameter WEI_TILE_K_LIM_LOWER_SIZE  = WEI_TILE_K_LIM_LOWER_MSB - WEI_TILE_K_LIM_LOWER_LSB + 1;

//IDX 35
parameter WEI_TILE_K_LIM_LSB         = 0;
parameter WEI_TILE_K_LIM_MSB         = WEI_TILE_DIM_SIZE - WEI_TILE_K_LIM_LOWER_SIZE - 1;
parameter WEI_TILE_K_LIM_SIZE        = WEI_TILE_K_LIM_MSB - WEI_TILE_K_LIM_LSB + 1;

parameter WEI_TILE_K_STEP_LSB        = WEI_TILE_K_LIM_MSB + 1;
    
parameter WEI_COLS_ACTIVE_LOWER_LSB  = WEI_TILE_K_STEP_LSB + WEI_TILE_DIM_SIZE;
parameter WEI_COLS_ACTIVE_LOWER_MSB  = SAURIA_REG_SIZE - 1;
parameter WEI_COLS_ACTIVE_LOWER_SIZE = WEI_COLS_ACTIVE_LOWER_MSB - WEI_COLS_ACTIVE_LOWER_LSB + 1;
   
//IDX 36
parameter WEI_COLS_ACTIVE_LSB        = 0;
parameter WEI_COLS_ACTIVE_SIZE       = COLS_ACTIVE_SIZE - WEI_COLS_ACTIVE_LOWER_SIZE;
parameter WEI_COLS_ACTIVE_MSB        = WEI_COLS_ACTIVE_LSB + WEI_COLS_ACTIVE_SIZE - 1;

parameter WEI_ALIGNED_FLAG_LSB       = WEI_COLS_ACTIVE_MSB + 1;

/**********PSUMS Dimensions********************* */

//IDX 37
parameter PSUMS_REPS_LSB                 = 0;
parameter PSUMS_CX_LIM_LSB               = PSUMS_REPS_LSB + PSUMS_TILE_DIM_SIZE;

parameter PSUMS_CX_STEP_LOWER_LSB        = PSUMS_CX_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CX_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CX_STEP_LOWER_SIZE       = PSUMS_CX_STEP_LOWER_MSB - PSUMS_CX_STEP_LOWER_LSB + 1;

//IDX 38
parameter PSUMS_CX_STEP_LSB              = 0;
parameter PSUMS_CX_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CX_STEP_LOWER_SIZE - 1;
parameter PSUMS_CX_STEP_SIZE             = PSUMS_CX_STEP_MSB - PSUMS_CX_STEP_LSB + 1;

parameter PSUMS_CK_LIM_LSB               = PSUMS_CX_STEP_MSB + 1;

parameter PSUMS_CK_STEP_LOWER_LSB        = PSUMS_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_CK_STEP_LOWER_MSB        = SAURIA_REG_SIZE - 1;
parameter PSUMS_CK_STEP_LOWER_SIZE       = PSUMS_CK_STEP_LOWER_MSB - PSUMS_CK_STEP_LOWER_LSB + 1;

//IDX 39
parameter PSUMS_CK_STEP_LSB              = 0;
parameter PSUMS_CK_STEP_MSB              = PSUMS_TILE_DIM_SIZE - PSUMS_CK_STEP_LOWER_SIZE - 1;
parameter PSUMS_CK_STEP_SIZE             = PSUMS_CK_STEP_MSB - PSUMS_CK_STEP_LSB + 1;

parameter PSUMS_TILE_CY_LIM_LSB          = PSUMS_CK_STEP_MSB + 1;

parameter PSUMS_TILE_CY_STEP_LOWER_LSB   = PSUMS_TILE_CY_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CY_STEP_LOWER_MSB   = SAURIA_REG_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_LOWER_SIZE  = PSUMS_TILE_CY_STEP_LOWER_MSB - PSUMS_TILE_CY_STEP_LOWER_LSB + 1;

//IDX 40
parameter PSUMS_TILE_CY_STEP_LSB         = 0;
parameter PSUMS_TILE_CY_STEP_MSB         = PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CY_STEP_LOWER_SIZE - 1;
parameter PSUMS_TILE_CY_STEP_SIZE        = PSUMS_TILE_CY_STEP_MSB - PSUMS_TILE_CY_STEP_LSB + 1;

parameter PSUMS_TILE_CK_LIM_LSB          = PSUMS_TILE_CY_STEP_MSB + 1;

parameter PSUMS_TILE_CK_STEP_LOWER_LSB   = PSUMS_TILE_CK_LIM_LSB + PSUMS_TILE_DIM_SIZE;
parameter PSUMS_TILE_CK_STEP_LOWER_MSB   = SAURIA_REG_SIZE - 1;
parameter PSUMS_TILE_CK_STEP_LOWER_SIZE  = PSUMS_TILE_CK_STEP_LOWER_MSB - PSUMS_TILE_CK_STEP_LOWER_LSB + 1;

parameter PSUMS_INACTIVE_COLS_LOWER_LSB  = SAURIA_REG_SIZE - 2; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_MSB  = SAURIA_REG_SIZE - 1; //INT-Only
parameter PSUMS_INACTIVE_COLS_LOWER_SIZE = PSUMS_INACTIVE_COLS_LOWER_MSB - PSUMS_INACTIVE_COLS_LOWER_LSB + 1; //INT-Only

//IDX 41
parameter PSUMS_TILE_CK_STEP_LSB         = 0;
parameter PSUMS_TILE_CK_STEP_MSB         = PSUMS_TILE_DIM_SIZE - PSUMS_TILE_CK_STEP_LOWER_SIZE - 1;
parameter PSUMS_TILE_CK_STEP_SIZE        = PSUMS_TILE_CK_STEP_MSB - PSUMS_TILE_CK_STEP_LSB + 1;

parameter PSUMS_INACTIVE_COLS_LSB        = PSUMS_TILE_CK_STEP_MSB + 1;
parameter PSUMS_INACTIVE_COLS_SIZE       = COLS_ACTIVE_SIZE;
parameter PSUMS_INACTIVE_COLS_MSB        = PSUMS_INACTIVE_COLS_LSB + PSUMS_INACTIVE_COLS_SIZE - 1;

parameter PSUMS_PRELOAD_EN_LSB           = PSUMS_INACTIVE_COLS_MSB + 1;
