$SAURIA/tb/packages/sauria_common_pkg.sv
+incdir+$SAURIA/tb/
+incdir+$SAURIA/tb/interfaces/
$SAURIA/tb/interfaces/sauria_df_controller_ifc.sv
$SAURIA/tb/interfaces/sauria_subsystem_ifc.sv
$SAURIA/tb/interfaces/sauria_axi_ifcs.sv
+incdir+$SAURIA/tb/interfaces/interface_connections/
+incdir+$SAURIA/tb/packages/
$SAURIA/tb/packages/sauria_base_cfg_seqs_pkg.sv
$SAURIA/tb/packages/sauria_cfg_seqs_pkg.sv
$SAURIA/tb/packages/sauria_golden_models_pkg.sv
$SAURIA/tb/packages/sauria_scbd_pkg.sv
$SAURIA/tb/packages/sauria_env_pkg.sv
$SAURIA/tb/packages/sauria_base_tests_pkg.sv
$SAURIA/tb/packages/sauria_cfg_tests_pkg.sv
$SAURIA/tb/packages/sauria_tb_top_pkg.sv
+incdir+$SAURIA/tb/coverage/
$SAURIA/tb/coverage/sauria_ss_cov.sv
+incdir+$SAURIA/tb/assertions/
$SAURIA/tb/assertions/sauria_ss_assert.sv
+incdir+$SAURIA/tb/golden_models/
+incdir+$SAURIA/tb/common/
+incdir+$SAURIA/tb/common/seq_items/
+incdir+$SAURIA/tb/common/seq_items/sauria_axi4_seq_items/
+incdir+$SAURIA/tb/common/seq_items/sauria_axi4_lite_seq_items/
+incdir+$SAURIA/tb/seqs/
+incdir+$SAURIA/tb/seqs/core_weights_cfg_seqs/
+incdir+$SAURIA/tb/seqs/df_controller_cfg_seqs/
+incdir+$SAURIA/tb/seqs/base_seqs/
+incdir+$SAURIA/tb/seqs/dma_controller_cfg_seqs/
+incdir+$SAURIA/tb/seqs/core_psums_cfg_seqs/
+incdir+$SAURIA/tb/seqs/core_ifmaps_cfg_seqs/
+incdir+$SAURIA/tb/seqs/core_main_controller_cfg_seqs/
+incdir+$SAURIA/tb/agents/
+incdir+$SAURIA/tb/agents/sauria_axi4_lite_agent/
+incdir+$SAURIA/tb/agents/sauria_axi4_agent/
+incdir+$SAURIA/tb/scoreboards/
$SAURIA/tb/tb_top.sv
